### ISSUE TITLE
Global properties

### ISSUE THREAD

**Issue by rodrigodalcindev** [sprangular/sprangular#174]
Global properties support should be improved through an augmented `Status` or route-based service. Some of these are essential to any web app and make front-end development work much easier, for example:
- Body tag identifiers (page or route-based classes and IDs)
- Meta tags (for SEO purposes, also page or route-based)
- Page titles (also page or route-based)

**Comment by rodrigodalcindev** [comment]
As a reminder, @simonwalsh suggests using Bower to achieve this.

**Comment by joshnuss** [comment]
We can add options for these to our routes (like how we added `requires: {user: true}`

Example:

```
$routeProvider
   .when '/foos',
       meta:
          keywords: 'fooseball, foose, foosing'
       title: 'Fooseball'
       layout:
          body:
             id: "foose-page"
             class: 'full'
       controller: 'FoosCtrl'
      
```
